from __future__ import annotations

from .config import DEFAULT_START_DATE, RAW_DIR, ROOT_DIR


PHASE2_RAW_DIR = RAW_DIR / "phase2"
PHASE2_PROCESSED_DIR = ROOT_DIR / "data" / "processed" / "phase2"
PHASE2_OUTPUTS_DIR = ROOT_DIR / "outputs" / "phase2"
PHASE2_SUMMARIES_DIR = PHASE2_OUTPUTS_DIR / "summaries"
PHASE2_METRICS_DIR = PHASE2_OUTPUTS_DIR / "metrics"
PHASE2_FIGURES_DIR = PHASE2_OUTPUTS_DIR / "figures"

PHASE2_DEFAULT_START_DATE = DEFAULT_START_DATE
PHASE2_SMOKE_START_DATE = "2024-01-01"

SOFR_SERIES_ID = "SOFR"
SOFR_SHORT_END_MONTHS = [1, 3, 6, 12]

PHASE2_GRID = sorted(
    {round(1.0 / 12.0, 6)}
    | {round(step * 0.25, 6) for step in range(1, 121)}
)
PROJECTION_GRID = [maturity for maturity in PHASE2_GRID if maturity >= 0.25]

PHASE2_SWAP_MATURITIES = [2.0, 5.0, 10.0]
FLOAT_TENOR_YEARS = 0.25
FIXED_TENOR_YEARS = 0.5
PHASE2_NOTIONAL = 100.0
PHASE2_DEFAULT_FIXED_COUPON = 0.03

PARALLEL_SHOCK_BP = 1.0
SLOPE_SHOCK_MAX_BP = 10.0
SLOPE_PIVOT_YEARS = 5.0
